# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[(b'de', 'German'), (b'en', 'English'), (b'fr', 'French'), (b'nl', 'Dutch'), (b'es', 'Spanish')], help_text='One of the languages defined in LANGUAGES', max_length=12, unique=True),
        ),
    ]
