# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 12:16
from __future__ import unicode_literals

from django.db import migrations


def create_site_tree(apps, schema_editor):
    Language = apps.get_model('wagtailtrans', 'Language')
    Page = apps.get_model('wagtailcore', 'Page')
    SiteRootPage = apps.get_model('wagtailtrans', 'TranslatableSiteRootPage')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    HomePage = apps.get_model('pages', 'HomePage')
    Site = apps.get_model('wagtailcore', 'Site')

    language, _ = Language.objects.get_or_create(is_default=True, defaults={
        'code': 'en',
        'position': 0,
        'live': True,
    })

    # Delete all pages except the `root` page
    Page.objects.exclude(depth=1).delete()

    # Create a new root page
    trans_root = SiteRootPage.objects.create(
        title='Translatable Root',
        slug='translatable-root',
        content_type=ContentType.objects.get_for_model(SiteRootPage),
        path='00010001',
        depth=2,
        numchild=1,
        url_path='/',
    )

    # Create a homepage in the default language.
    HomePage.objects.create(
        title='Homepage',
        subtitle='A sample homepage',
        slug=language.code,
        language=language,
        content_type=ContentType.objects.get_for_model(HomePage),
        path='000100010001',
        depth=3,
        numchild=0,
        url_path='/{}/'.format(language.code),
    )

    # Create a site with the new root_page as root
    Site.objects.create(
        hostname='localhost',
        port=8000,
        root_page=trans_root,
        is_default_site=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site_tree),
    ]
