# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('pages', '0002_auto_20160930_1042'),
        ('wagtailtrans', '0006_auto_20161212_2020'),
    ]

    operations = [
        migrations.RunSQL(
            """
            BEGIN;

            -- Add the ``page_ptr_id`` field in the DB.
            ALTER TABLE pages_homepage ADD COLUMN page_ptr_id INTEGER UNIQUE;
            UPDATE pages_homepage SET page_ptr_id=translatablepage_ptr_id;
            ALTER TABLE pages_homepage ALTER COLUMN page_ptr_id DROP DEFAULT;
            ALTER TABLE pages_homepage ALTER COLUMN page_ptr_id SET NOT NULL;
            ALTER TABLE pages_homepage ADD CONSTRAINT pages_homepage_page_ptr_id_5b805d74_fk_wagtailcore_page_id FOREIGN KEY (page_ptr_id) REFERENCES wagtailcore_page (id) DEFERRABLE INITIALLY DEFERRED;

            COMMIT;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='homepage',
                    name='page_ptr',
                    field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page'),
                    preserve_default=False,
                ),
            ]
        ),
    ]
