# Generated by Django 2.1.7 on 2019-02-18 15:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailtrans.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailtrans', '0008_auto_20190218_1502'),
        ('pages', '0002_auto_20161214_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixinHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(help_text='A required field, for test purposes', max_length=255)),
                ('body', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('canonical_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='pages.MixinHomePage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('language', models.ForeignKey(default=wagtailtrans.models._language_default, on_delete=django.db.models.deletion.PROTECT, to='wagtailtrans.Language')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
