# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:38
from __future__ import unicode_literals

from django.db import migrations


def create_page_structure(apps, schema_editor):
    TranslationHomePage = apps.get_model('sandbox', 'TranslationHomePage')
    HomePage = apps.get_model('sandbox', 'HomePage')
    Language = apps.get_model('wagtailtrans', 'Language')
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')

    # Delete the default root- and homepage
    Page.objects.filter(id=2).delete()

    lang, created = Language.objects.get_or_create(
        code='en',
        is_default=True,
        order=1,
        live=True
    )

    # Create a new rootpage
    trans_root = TranslationHomePage.objects.create(
        title='translation root',
        slug='translation-root',
        content_type=ContentType.objects.get_for_model(TranslationHomePage),
        path='00010001',
        depth=2,
        numchild=1,
        url_path='/',
    )

    homepage = HomePage.objects.create(
        title='homepage',
        slug='home',
        language=lang,
        content_type=ContentType.objects.get_for_model(HomePage),
        path='000100010001',
        depth=3,
        numchild=0,
        url_path='/home/',
    )

    # Create a site with the new homepage set as the root
    Site.objects.create(
        hostname='localhost', root_page=trans_root, is_default_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_page_structure)
    ]
